import { Clapperboard, Music, Sliders, Sparkles, Video, VolumeX, Zap } from 'lucide-react';
import type { FfmpegPreset } from './types';

export const PRESET_LIST: FfmpegPreset[] = [
  {
    id: 'lossless-trim',
    name: '極速無損剪切',
    mode: 'copy',
    badge: '推薦',
    icon: Zap,
    desc: '無損複製 -c copy，零轉檔時間維持 100% 原始畫質',
  },
  {
    id: 'high-quality-h264',
    name: 'H.264 高相容',
    mode: 'reencode',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    resolution: 'original',
    icon: Video,
    desc: '適用於幾乎所有社群平台、播放器與手機',
  },
  {
    id: 'efficient-h265',
    name: 'H.265 高壓縮',
    mode: 'reencode',
    videoCodec: 'libx265',
    audioCodec: 'aac',
    crf: 26,
    preset: 'medium',
    resolution: 'original',
    icon: Sliders,
    desc: '體積大幅縮小 40%，維持細膩清晰畫質',
  },
  {
    id: 'vertical-shorts',
    name: '9:16 直式 Shorts',
    mode: 'reencode',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 22,
    preset: 'fast',
    resolution: 'shorts_9_16',
    icon: Clapperboard,
    desc: '等比居中縮放並補黑邊至 1080x1920 直式畫面',
  },
  {
    id: 'extract-audio-mp3',
    name: '擷取 MP3 音訊',
    mode: 'audio',
    videoCodec: 'none',
    audioCodec: 'libmp3lame',
    audioBitrate: '192k',
    outputExt: 'mp3',
    icon: Music,
    desc: '移除視訊軌，輸出高品質 192kbps MP3 聲音檔',
  },
  {
    id: 'mute-video',
    name: '影片靜音 (移除音訊)',
    mode: 'reencode',
    videoCodec: 'copy',
    audioCodec: 'none',
    icon: VolumeX,
    desc: '完全移除聲音軌道，保留無損視訊流',
  },
  {
    id: 'animated-gif',
    name: '動態 GIF 圖片',
    mode: 'gif',
    outputExt: 'gif',
    icon: Sparkles,
    desc: '使用兩階段調色盤最佳化演算法產生高畫質 GIF',
  },
];
